import { useEffect, useMemo, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BarChart3, Check, ChevronDown, Facebook, Filter, Instagram, LayoutDashboard, LogOut, Menu, Search, Settings, ShieldCheck, Sparkles, Tag, Trash2, Twitter, UserRound, Users, X } from 'lucide-react'
import { categories as seedCategories, profiles as seedProfiles } from './data'
import { supabase } from './lib/supabase'
import { useSiteContent } from './lib/siteContent'
import type { Category, Profile } from './types'
import AdminWorkspace from './AdminWorkspace'

const ink = '#183d34'
const formatDate = (date: string) => new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date))

function useProfiles() {
  const [items, setItems] = useState<Profile[]>(seedProfiles)
  useEffect(() => {
    const client = supabase
    if (!client) return
    let active = true
    const load = async () => {
      const { data, error } = await client.from('profiles').select('*, category:categories(name)').eq('is_published', true).order('created_at', { ascending: false })
      if (error) { console.error('Could not load published profiles:', error); return }
      if (active) setItems((data || []).map((item: any) => ({ ...item, category: Array.isArray(item.category) ? item.category[0]?.name : item.category?.name })))
    }
    void load()
    const channel = client.channel('public-profiles-live').on('postgres_changes', { event: '*', schema: 'public', table: 'profiles' }, () => { void load() }).subscribe()
    return () => { active = false; void client.removeChannel(channel) }
  }, [])
  return { profiles: items, setProfiles: setItems }
}

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><Link to="/" className="brand"><span className="brand-mark">SB</span><span>Sapangan <i>Boys</i></span></Link><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Menu size={22} /></button><nav className={open ? 'nav open' : 'nav'}><Link to="/">Home</Link><Link to="/boys">Boys</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/admin/login" className="nav-admin">Admin <ArrowUpRight size={15} /></Link></nav></header>
}
function Footer() { return <footer><div className="footer-top"><Link to="/" className="brand"><span className="brand-mark">SB</span><span>Sapangan <i>Boys</i></span></Link><p>A living collection of stories, energy, and everyday magic from Sapangan.</p><div className="socials"><a href="#" aria-label="Facebook"><Facebook size={17} /></a><a href="#" aria-label="Instagram"><Instagram size={17} /></a><a href="#" aria-label="Twitter"><Twitter size={17} /></a></div></div><div className="footer-bottom"><span>© 2024 Sapangan Boys</span><span>Made with care in San Juan, Batangas</span><Link to="/contact">Request profile removal</Link></div></footer> }
function Shell({ children }: { children: React.ReactNode }) { return <><Header />{children}<Footer /></> }
function Image({ src, name }: { src: string; name: string }) { return <img src={src} alt={name} onError={(event) => { event.currentTarget.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=d7e5db&color=183d34&size=900` }} /> }
function ProfileCard({ profile }: { profile: Profile }) { return <article className="profile-card"><Link to={`/profile/${profile.id}`} className="card-image"><Image src={profile.profile_image_url} name={profile.display_name} /><span className="card-arrow"><ArrowUpRight size={18} /></span></Link><div className="card-content"><span className="eyebrow">{profile.category || 'Community'}</span><h3>{profile.display_name}</h3><p>{profile.short_description}</p><div className="tag-row">{profile.interests.slice(0, 3).map((interest) => <span key={interest}>{interest}</span>)}</div><Link to={`/profile/${profile.id}`} className="text-link">View profile <ArrowRight size={15} /></Link></div></article> }
function SectionHeading({ kicker, title, body }: { kicker: string; title: string; body?: string }) { return <div className="section-heading"><span className="eyebrow">{kicker}</span><h2>{title}</h2>{body && <p>{body}</p>}</div> }

function Home() { const { profiles } = useProfiles(); return <Shell><main><section className="hero"><div className="hero-copy"><div className="eyebrow light"><span className="dot" /> Sapangan, San Juan, Batangas</div><h1>Good people.<br /><em>Good stories.</em></h1><p>Discover the personalities, passions, and everyday energy that make our corner of Batangas feel like home.</p><Link to="/boys" className="button button-light">Explore profiles <ArrowRight size={17} /></Link></div><div className="hero-art"><div className="sun" /><div className="hero-note"><Sparkles size={17} /><span>Community<br /><b>in full color</b></span></div><div className="hero-photo photo-one"><Image src={profiles[1].profile_image_url} name={profiles[1].display_name} /></div><div className="hero-photo photo-two"><Image src={profiles[0].profile_image_url} name={profiles[0].display_name} /></div><div className="leaf leaf-one">✳</div><div className="leaf leaf-two">✦</div></div></section><section className="intro"><div className="intro-number">01 <span /></div><div><SectionHeading kicker="The idea" title="A closer look at home." body="Sapangan Boys is a community profile project for the people who make Sapangan vibrant. No big stage needed, just real interests, honest stories, and a little room to be seen." /><Link to="/about" className="text-link">Our story <ArrowRight size={15} /></Link></div><div className="intro-stamp"><ShieldCheck size={22} /><span>Built on<br /><b>consent & care</b></span></div></section><section className="featured"><div className="featured-head"><SectionHeading kicker="The latest" title="Meet the boys" body="A few familiar faces from around the neighborhood." /><Link to="/boys" className="button button-outline">See all profiles <ArrowRight size={16} /></Link></div><div className="profile-grid">{profiles.slice(0, 4).map((profile) => <ProfileCard profile={profile} key={profile.id} />)}</div></section><section className="quote-band"><div className="quote-mark">“</div><blockquote>Every person carries a story worth knowing.</blockquote><span>— The Sapangan Boys community</span></section></main></Shell> }

function Boys() { const content = useSiteContent(); const { profiles } = useProfiles(); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All interests'); const [sort, setSort] = useState('Newest first'); const filtered = useMemo(() => profiles.filter(p => `${p.display_name} ${p.short_description} ${p.interests.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All interests' || p.category === category)).sort((a, b) => sort === 'Newest first' ? b.created_at.localeCompare(a.created_at) : a.display_name.localeCompare(b.display_name)), [profiles, query, category, sort]); return <Shell><main className="page"><div className="directory-head"><div><span className="eyebrow">The directory</span><h1>People of <em>Sapangan.</em></h1><p>{content.boys_intro}</p></div><div className="directory-count"><b>{filtered.length}</b><span>profiles<br />shown</span></div></div><div className="filters"><div className="search-box"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name or interest..." /></div><div className="select-box"><Filter size={16} /><select value={category} onChange={e => setCategory(e.target.value)}><option>All interests</option>{seedCategories.map(c => <option key={c.id}>{c.name}</option>)}</select><ChevronDown size={15} /></div><div className="select-box sort"><select value={sort} onChange={e => setSort(e.target.value)}><option>Newest first</option><option>Name A–Z</option></select><ChevronDown size={15} /></div></div>{filtered.length ? <div className="profile-grid directory-grid">{filtered.map(profile => <ProfileCard profile={profile} key={profile.id} />)}</div> : <div className="empty"><Search size={30} /><h3>No profiles found</h3><p>Try a different name, interest, or category.</p></div>}</main></Shell> }

function ProfileDetails() { const { id } = useParams(); const { profiles } = useProfiles(); const profile = profiles.find(p => p.id === id); if (!profile) return <Shell><div className="empty page"><h2>Profile not found</h2><Link to="/boys" className="text-link">Back to profiles <ArrowRight size={15} /></Link></div></Shell>; return <Shell><main className="detail-page"><Link to="/boys" className="back-link">← Back to profiles</Link><div className="detail-layout"><div className="detail-image"><Image src={profile.profile_image_url} name={profile.display_name} /><span>{profile.category}</span></div><div className="detail-copy"><span className="eyebrow">A Sapangan profile</span><h1>{profile.display_name}</h1><p className="detail-lede">{profile.short_description}</p><div className="detail-rule" /><p>{profile.bio}</p><div className="detail-sections"><div><b>Hobbies</b><div className="detail-tags">{profile.hobbies.map(h => <span key={h}>{h}</span>)}</div></div><div><b>Interests</b><div className="detail-tags">{profile.interests.map(i => <span key={i}>{i}</span>)}</div></div></div><small>Added {formatDate(profile.created_at)}</small></div></div></main></Shell> }
function About() { const content = useSiteContent(); return <Shell><main className="simple-page"><span className="eyebrow">About the project</span><h1>{content.about_heading.split('. ')[0]}.<br /><em>{content.about_heading.split('. ').slice(1).join('. ')}</em></h1><p className="large-copy">{content.about_body}</p><div className="about-grid"><div><b>Why it exists</b><p>Home is more than a pin on a map. This is a space to celebrate the people, energy, and stories that make Sapangan special.</p></div><div><b>Our promise</b><p>Every profile is published only with the person's permission. We keep private information private and make removal requests easy.</p></div></div><Link to="/boys" className="button button-dark">Meet the community <ArrowRight size={16} /></Link></main></Shell> }
function Contact() { const content = useSiteContent(); return <Shell><main className="simple-page contact-page"><span className="eyebrow">Get in touch</span><h1>Keep the community<br /><em>in the loop.</em></h1><p className="large-copy">{content.contact_body}</p><a className="contact-email" href={`mailto:${content.contact_email}`}>{content.contact_email} <ArrowUpRight size={20} /></a><p className="privacy-note"><ShieldCheck size={18} /> Profiles are public by design. We only share information that people have voluntarily provided and approved.</p></main></Shell> }

function AdminLayout({ children }: { children: React.ReactNode }) { const nav = useNavigate(); return <div className="admin-shell"><aside className="admin-side"><Link to="/admin/dashboard" className="brand"><span className="brand-mark">SB</span><span>Sapangan <i>Boys</i></span></Link><div className="admin-label">Workspace</div><Link to="/admin/dashboard"><LayoutDashboard size={17} /> Overview</Link><Link to="/admin/manage"><Users size={17} /> Manage website</Link><Link to="/admin/profiles"><Users size={17} /> Profiles</Link><Link to="/admin/profiles/new"><Sparkles size={17} /> Add profile</Link><Link to="/admin/categories"><Tag size={17} /> Categories</Link><div className="admin-label">Account</div><Link to="/admin/settings"><Settings size={17} /> Settings</Link><button onClick={async () => { await supabase?.auth.signOut(); nav('/admin/login') }}><LogOut size={17} /> Log out</button></aside><div className="admin-main"><header className="admin-top"><span>Saturday, June 15, 2024</span><Link to="/" className="view-site">View public site <ArrowUpRight size={15} /></Link></header>{children}</div></div> }
function RequireAdmin() { const [status, setStatus] = useState<'loading' | 'signed-in' | 'signed-out'>('loading'); useEffect(() => { if (!supabase) { setStatus('signed-out'); return } supabase.auth.getSession().then(({ data }) => setStatus(data.session ? 'signed-in' : 'signed-out')); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setStatus(session ? 'signed-in' : 'signed-out')); return () => listener.subscription.unsubscribe() }, []); if (status === 'loading') return <div className="empty page"><p>Checking admin session...</p></div>; return status === 'signed-in' ? <AdminLayout><Routes><Route path="/dashboard" element={<Dashboard />} /><Route path="/manage" element={<AdminWorkspace />} /><Route path="/profiles" element={<AdminProfiles />} /><Route path="/profiles/new" element={<ProfileForm />} /><Route path="/profiles/:id/edit" element={<ProfileForm />} /><Route path="/categories" element={<Categories />} /><Route path="/settings" element={<AdminWorkspace />} /></Routes></AdminLayout> : <Navigate to="/admin/login" replace /> }
function AdminLogin() { const nav = useNavigate(); const [email, setEmail] = useState('admin@gmail.com'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); if (!supabase) { setError('Supabase is not configured for this deployment.'); return } const result = await supabase.auth.signInWithPassword({ email, password }); if (result.error) { setError(result.error.message); return } nav('/admin/dashboard') }; return <div className="login-page"><Link to="/" className="brand"><span className="brand-mark">SB</span><span>Sapangan <i>Boys</i></span></Link><form className="login-card" onSubmit={submit}><span className="eyebrow">Admin workspace</span><h1>Welcome back.</h1><p>Sign in to manage your community profiles.</p><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" /></label>{error && <small className="form-error">{error}</small>}<button className="button button-dark" type="submit">Sign in <ArrowRight size={16} /></button><small>Public visitors do not need an account.</small></form></div> }
function Dashboard() { const { profiles } = useProfiles(); return <div className="admin-content"><div className="admin-title"><div><span className="eyebrow">Overview</span><h1>Good morning, admin.</h1></div><Link to="/admin/profiles/new" className="button button-dark"><Sparkles size={16} /> Add profile</Link></div><div className="stats"><div><span><Users size={17} /> Total profiles</span><b>{profiles.length}</b><small>Across the community</small></div><div><span><Check size={17} /> Published</span><b>{profiles.filter(p => p.is_published).length}</b><small>Visible to everyone</small></div><div><span><BarChart3 size={17} /> Drafts</span><b>0</b><small>Waiting for review</small></div><div><span><Tag size={17} /> Categories</span><b>{seedCategories.length}</b><small>Active categories</small></div></div><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">Recently added</span><h2>Latest profiles</h2></div><Link to="/admin/profiles" className="text-link">Manage all <ArrowRight size={15} /></Link></div><AdminTable profiles={profiles.slice(0, 3)} /></div></div> }
function AdminTable({ profiles }: { profiles: Profile[] }) { return <div className="table-wrap"><table><thead><tr><th>Profile</th><th>Category</th><th>Status</th><th>Date added</th><th /></tr></thead><tbody>{profiles.map(p => <tr key={p.id}><td><div className="table-profile"><Image src={p.profile_image_url} name={p.display_name} /><b>{p.display_name}</b></div></td><td>{p.category}</td><td><span className="status"><i /> Published</span></td><td>{formatDate(p.created_at)}</td><td><Link to={`/admin/profiles/${p.id}/edit`} className="icon-button" aria-label="Edit"><ArrowUpRight size={16} /></Link></td></tr>)}</tbody></table></div> }
function AdminProfiles() { const { profiles } = useProfiles(); return <div className="admin-content"><div className="admin-title"><div><span className="eyebrow">Content management</span><h1>Profiles</h1></div><Link to="/admin/profiles/new" className="button button-dark"><Sparkles size={16} /> Add profile</Link></div><div className="admin-panel"><AdminTable profiles={profiles} /></div></div> }
function ProfileForm() { const nav = useNavigate(); const { id } = useParams(); const existing = seedProfiles.find(p => p.id === id); const [name, setName] = useState(existing?.display_name || ''); const [description, setDescription] = useState(existing?.short_description || ''); const [bio, setBio] = useState(existing?.bio || ''); const [consent, setConsent] = useState(existing?.consent_confirmed || false); const [image, setImage] = useState<File>(); const submit = async (e: React.FormEvent) => { e.preventDefault(); let imageUrl = existing?.profile_image_url || ''; if (supabase && image) { const path = `${crypto.randomUUID()}-${image.name}`; const upload = await supabase.storage.from('profile-images').upload(path, image); if (!upload.error) imageUrl = supabase.storage.from('profile-images').getPublicUrl(path).data.publicUrl } if (supabase) { const payload = { display_name: name, short_description: description, bio, profile_image_url: imageUrl, consent_confirmed: consent, is_published: consent }; const result = id ? await supabase.from('profiles').update(payload).eq('id', id) : await supabase.from('profiles').insert(payload); if (result.error) return } nav('/admin/profiles') }; return <div className="admin-content"><div className="admin-title"><div><span className="eyebrow">{id ? 'Edit profile' : 'New profile'}</span><h1>{id ? 'Update a profile.' : 'Add someone new.'}</h1></div></div><form className="profile-form" onSubmit={submit}><div className="form-main"><label>Display name<input required value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Juan Dela Cruz" /></label><label>Short description<textarea required value={description} onChange={e => setDescription(e.target.value)} placeholder="A sentence that captures their energy..." /></label><label>Biography<textarea className="tall" value={bio} onChange={e => setBio(e.target.value)} placeholder="Tell their story..." /></label></div><aside className="form-side"><div className="upload"><Sparkles size={22} /><b>Profile image</b><span>JPG or PNG, max 5MB</span><input type="file" accept="image/png,image/jpeg" onChange={e => setImage(e.target.files?.[0])} /></div><label>Category<select><option>Select a category</option>{seedCategories.map(c => <option key={c.id}>{c.name}</option>)}</select></label><label>Hobbies<input placeholder="Basketball, music..." /></label><label>Interests<input placeholder="Community, travel..." /></label><label className="consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /><span><b>Permission confirmed</b><small>I confirm this person has given permission for their image and information to be displayed publicly.</small></span></label><button disabled={!consent} className="button button-dark" type="submit">Save profile <ArrowRight size={16} /></button></aside></form></div> }
function Categories() { return <div className="admin-content"><div className="admin-title"><div><span className="eyebrow">Organize your directory</span><h1>Categories</h1></div><button className="button button-dark"><Tag size={16} /> Add category</button></div><div className="category-list">{seedCategories.map(c => <div key={c.id}><div className="category-icon"><Tag size={18} /></div><div><b>{c.name}</b><p>{c.description}</p></div><span>{seedProfiles.filter(p => p.category_id === c.id).length} profiles</span><button className="icon-button"><Trash2 size={16} /></button></div>)}</div></div> }

export default function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/boys" element={<Boys />} /><Route path="/profile/:id" element={<ProfileDetails />} /><Route path="/about" element={<About />} /><Route path="/contact" element={<Contact />} /><Route path="/admin/login" element={<AdminLogin />} /><Route path="/admin/*" element={<RequireAdmin />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes> }
